package com.app_investigarte.fragments.Map

import com.google.android.gms.maps.GoogleMap
import com.google.android.gms.maps.model.LatLng
import com.google.android.gms.maps.model.PolylineOptions

object MapAntioquia {
    /*
    fun mapaAntioquia(mMap: GoogleMap, colorMap: Int) {
        // Add Polyline
        mMap.addPolyline(
            PolylineOptions()
                .add(
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(), LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                    LatLng(),
                )
                .width(10f)
                .color(colorMap)
        )


        // Add Polyline
        mMap.addPolyline(
            PolylineOptions()
                .add(
                    LatLng(8.678973577364099, -77.37136434763669),
                    LatLng(8.64233938741097, -77.37324222922325),
                    LatLng(8.635531610066707, -77.37349234521389),
                    LatLng(8.650508027591828, -77.39227116107939),
                    LatLng(8.649641584705197, -77.39602692425251),
                    LatLng(8.641351276218499, -77.41029699476398),
                    LatLng(8.616615169294397, -77.40059304982424),
                    LatLng(8.584929851675662, -77.3918329551816),
                    LatLng(8.584561940236966, -77.4189966917038),
                    LatLng(8.568211614057303, -77.41038613021374),
                    LatLng(8.587451712781142, -77.41911605000496),
                    LatLng(8.568128398970348, -77.40938264876604),
                    LatLng(8.557762839519858, -77.42652866989374),
                    LatLng(8.56291001412214, -77.4364826595068),
                    LatLng(8.5128679640736, -77.44358584284782),
                    LatLng(8.507988978787042, -77.455479428117211),
                    LatLng(8.47226948154305, -77.446363940835),
                    LatLng(8.469601610677092, -77.43689416992664),
                    LatLng(8.47479739232696, -77.4017534404993),
                    LatLng(7.928547286052519, -77.16720096766947),
                    LatLng(7.9120274098592445, -77.28656999766825),
                    LatLng(7.8295284001180026, -77.35370334237814),
                    LatLng(7.775239837903687, -77.33529534190893),
                    LatLng(7.76397987171479, -77.38436669111252),
                    LatLng(7.664011025848014, -77.43980593979359),
                    LatLng(7.505470646653843, -77.57457822561264),
                    LatLng(7.658005001526036, -77.64879159629345),
                    LatLng(7.683901575658946, -77.72584475576878),
                    LatLng(7.603741934641177, -77.74183575063945),
                    LatLng(7.439701627916182, -77.71004654467106),
                    LatLng(7.453375566397509, -77.81595256179571),
                    LatLng(7.226332694276445, -77.8917048498988)
                )
                .width(10f)
                .color(colorMap)
        )
    }
*/
}
